### ISSUE TITLE
array profil

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-twig#1]
```
'profil' =>[
        [
            'img' => 'img/renaldy.png',
            'profil' => 'MY PROFILE',
            'nama' => 'Renaldy Permana Sundawa',
            'ttl' => 'Surabaya, 12 Mei 2003',
            'alamat' => 'Jl. Tenggumung baru no 170',
            'no_telp' => ':+6281248689876',
            'email' => 'renaldypermana7@gmail.com',
            'hobi' => 'Berenang dan Berlari',
        ]
    ],
```

karena array profil hanya berisi 1 data profil maka tidak perlu dibuat array 2D, cukup array 1D saja

sehingga ketika ditampilkan tidak perlu menggunakan looping/iteration

**Comment by Fakhri17** [comment]
![image](https://user-images.githubusercontent.com/54692387/66619633-d5f46280-ec07-11e9-8a57-fdbbfd677b2c.png)

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/66658672-243b4d00-ec6c-11e9-965e-659caf37a339.png)
